In [14]:
import numpy as np
import pandas as pd
from scipy.spatial import distance
import math
import matplotlib.pyplot as plt

# global variables
points = []
target_dimension = 1
mapped = np.zeros((5, target_dimension), dtype = np.float)
pivots = np.zeros((1, 2), dtype = np.int)
colNum = 0


dist_array = np.array(([
                        [0,2,1,3,4], 
                        [2,0,1,3,3],
                        [1,1,0,3,3],
                        [3,3,3,0,1],
                        [4,3,3,1,0]
                        ]),
                      dtype = np.float)


def dist(obj_a, obj_b):
    '''
        return L2 distance
    '''
    dis = 0
    for i in range(len(obj_a)):
        dis += (obj_a[i] - obj_b[i])**2
    return math.sqrt(dis)


def init_distances():
    '''
        create distance matrix: dist_array[N][N]
        dist_array[i][j] is the distance between object i and j in original space
    '''
    for x in range(0, 8):
        for y in range(0, 8): 
            dist_array[x][y] = dist(points[x], points[y])
    
    return None


def choose_dist_obj(distances):
    '''
        find two points whose distance is the longest
    '''
    # randomly choose object b
    obj_b = np.random.randint(0,5)
    print('randomly choose obj_b', obj_b)
    # Iterate until convergence
    while True: 
        # use the distance matrix 

        # find the farthest object from object b
        farthest = max(distances[obj_b])
        obj_a = distances[obj_b].tolist().index(farthest)

        # find the farthest object from object a
        tmp = max(distances[obj_a])
        tmpObj = distances[obj_a].tolist().index(tmp)

        # when the farthest object of object a is exatly object b,
        # it converges
        if (tmpObj == obj_b):
            break
        else:
            obj_b = tmpObj

    # return a smaller object id
    if obj_a < obj_b:
        print('obj_a', obj_a, 'obj_b', obj_b)
        return (obj_a, obj_b)
    else:
        print('obj_b', obj_b, 'obj_a', obj_a)
        return (obj_b, obj_a)
        


def fastMap(k, distances):
    '''
        k: target dimension
        distances: distance matrix or last projection
        This function will be called recursively.
    '''
    global colNum

    # recursion exit point
    if k <= 0:
        return None
    else:
        pass
        # colNum += 1
    
    # choose pivot object
    pivots = choose_dist_obj(distances)
    
    a = pivots[0]   # pivot a
    b = pivots[1]   # pivot b

    farthest = distances[a][b]
    if farthest == 0:
        for i in range(len(points)):
            mapped[i][colNum] = 0

    # project objects on line(Oa, Ob)
    for i in range(0, len(distances)):
        temp = 0
        if i == a:
            mapped[i][colNum] = 0
        elif i == b:
            mapped[i][colNum] = farthest
        else:
            # cosine law
            temp = ((distances[a][i]**2) + (farthest**2) - (distances[b][i]**2))/(2 * farthest)
            mapped[i][colNum] = temp

    # update distance matrix
    # projection will be the new distance matrix after dimension reduction
    projection = np.zeros((5, 5))
    for i in range (5):
        for j in range (5):
            # dimensional reduction
            tmp = (distances[i][j] ** 2) - ((mapped[i][colNum] - mapped[j][colNum]) ** 2)
            projection[i][j] = np.sqrt(np.absolute(tmp))

    colNum += 1

    # recursion
    fastMap(k-1, projection)

    return None


def main():

    print(dist_array)
    fastMap(target_dimension, dist_array)
    print('Answer:')
    print(mapped)
    print()
    return None


main()


[[0. 2. 1. 3. 4.]
 [2. 0. 1. 3. 3.]
 [1. 1. 0. 3. 3.]
 [3. 3. 3. 0. 1.]
 [4. 3. 3. 1. 0.]]
randomly choose obj_b 1
obj_b 0 obj_a 4
Answer:
[[0.   ]
 [1.375]
 [1.   ]
 [3.   ]
 [4.   ]]

