In [11]:
import numpy as np

matrix = np.array([[1, 2, 0, 0],
                    [1, 1, 0, 1],
                    [3, 4, 0, 0],
                    [1, 1, 1, 0],
                    [0, 1, 2, 3], 
                    [0, 0, 2, 3]])

matrix2 = np.array([[1, 1, 1],
                    [0, 1, 1],
                    [1, 0, 0],
                    [0, 1, 0],
                    [1, 0, 0], 
                    [1, 0, 1],
                    [1, 1, 1],
                    [1, 1, 1],
                    [1, 0, 1],
                     [0, 2, 0],
                     [0, 1, 1]])

matrix3 = np.array([[1, 0, 1, 0, 0, 0],
                   [0, 1, 0, 0, 0, 0],
                   [1, 1, 0, 0, 0, 0],
                   [1, 0, 0, 1, 1, 0],
                   [0, 0, 0, 1, 0, 1]])

u, s, v = np.linalg.svd(matrix)

print('v')
print(v)

s[2], s[3] = 0,0
uk = u[:, :2]
Sk = np.zeros([2, 2])
for i in range(2):
    Sk[i][i] = s[i]
vk = v[:2, :]
# print(np.dot(u, S))
print
print('uk')
print(uk)
print('Sk')
print(Sk)
print('vk')
print(vk)

print(np.dot(np.dot(uk, Sk), vk))


q1 = np.array([[1,1,0,0,0,0]])

print(q1.T)

u = np.array([[-0.32, 0.19], [-0.26, -0.02], [-0.73, 0.45], [-0.24, 0.03], [-0.38, -0.58], [-0.26, -0.64]])
             
s = np.array([[0.16, 0], [0, 0.2]])

ans = np.dot(np.dot(q1, u), s)

print(ans)

def cosine(q, d):
    # denominator = math.sqrt(np.sum([q[i] ** 2 for i in range(len(q))])) * math.sqrt(sum([d[i] ** 2 for i in range(len(d))]))
    denominator = np.linalg.norm(q) * np.linalg.norm(d)
    numerator = np.sum(np.multiply(q, d))
    # numerator = np.dot(q, d)
    return numerator / denominator

doc = [[-0.50, 0.31], [-0.74, 0.32], [-0.25, -0.48], [-0.36, -0.74]]

similarity = []

for d in doc:
    similarity.append(cosine(ans, d))
        
print(similarity)

v
[[-0.50199747 -0.74086598 -0.25546341 -0.36586142]
 [ 0.31274394  0.32533358 -0.48877364 -0.74662549]
 [-0.08251971  0.07481046 -0.83235839  0.54293038]
 [-0.80210988  0.58281992  0.05493882 -0.11799324]]
uk
[[-0.32678139  0.19387279]
 [-0.26500658 -0.02184374]
 [-0.73625724  0.45068086]
 [-0.24682062  0.03004528]
 [-0.38701483 -0.58199205]
 [-0.26497136 -0.64746081]]
Sk
[[6.07050922 0.        ]
 [0.         4.969295  ]]
vk
[[-0.50199747 -0.74086598 -0.25546341 -0.36586142]
 [ 0.31274394  0.32533358 -0.48877364 -0.74662549]]
[[ 1.29712815  1.78310762  0.03588034  0.0064628 ]
 [ 0.77362811  1.15653523  0.46402573  0.66961505]
 [ 2.94406654  4.0398742   0.04714167 -0.03691549]
 [ 0.79885019  1.15863296  0.3097919   0.43670592]
 [ 0.27489768  0.79967951  2.01375734  3.01885467]
 [-0.19876128  0.14495518  1.98350766  2.99070273]]
[[1]
 [1]
 [0]
 [0]
 [0]
 [0]]
[[-0.0928  0.034 ]]
[0.9793036982900459, 0.9983783524081613, 0.12862621313593228, 0.1014123645654397]


In [6]:
import numpy as np

# m = np.array([[1, 0, 1, 0, 0, 0],
#                 [0, 1, 0, 0,0,0],
#                 [1, 1, 0, 0, 0,0],
#                 [1,0, 0,1,1,0],
#                 [0, 0, 0, 1,0,1]])

m = np.array([[1, 2, 0, 0],
                    [1, 1, 0, 1],
                    [3, 4, 0, 0],
                    [1, 1, 1, 0],
                    [0, 1, 2, 3], 
                    [0, 0, 2, 3]])

u, s, v = np.linalg.svd(m)

u[:,2:] = 0
v[2:,:] = 0
v = v[:-1,:]
print(u)
print(s)
print(v)

S = np.zeros([6, 6])
for i in range(2):
    S[i][i] = s[i]
print(S)

print(u.shape)
print(S.shape)
print(v.shape)

np.array()

print(np.concatenate(v, np.zeros(1,v.shape(1)), axix=0))

print(np.dot(np.dot(u, S), v))

[[-0.32678139  0.19387279  0.          0.          0.          0.        ]
 [-0.26500658 -0.02184374  0.          0.          0.          0.        ]
 [-0.73625724  0.45068086  0.          0.          0.          0.        ]
 [-0.24682062  0.03004528  0.          0.          0.          0.        ]
 [-0.38701483 -0.58199205  0.          0.          0.          0.        ]
 [-0.26497136 -0.64746081  0.          0.          0.          0.        ]]
[6.07050922 4.969295   1.00107525 0.67295868]
[[-0.50199747 -0.74086598 -0.25546341 -0.36586142]
 [ 0.31274394  0.32533358 -0.48877364 -0.74662549]
 [ 0.          0.          0.          0.        ]]
[[6.07050922 0.         0.         0.         0.         0.        ]
 [0.         4.969295   0.         0.         0.         0.        ]
 [0.         0.         0.         0.         0.         0.        ]
 [0.         0.         0.         0.         0.         0.        ]
 [0.         0.         0.         0.         0.         0.        ]
 [0.

TypeError: Required argument 'object' (pos 1) not found

In [53]:
import numpy as np
import scipy.spatial

X = np.array([3, 1, 1])
Y = np.array([1, 3, 3, 2, 1, 3, 2, 4])

C = scipy.spatial.distance.cdist(X[:, np.newaxis], Y[:, np.newaxis], 'euclidean')
print('Cost matrix C =', C, sep='\n')

def compute_accumulated_cost_matrix(C):
    """Given the cost matrix, compute the accumulated cost matrix for subsequence dynamic time warping with
    step sizes {(1, 0), (0, 1), (1, 1)}

    Notebook: C7/C7S2_SubsequenceDTW.ipynb

    Args:
        C: cost matrix

    Returns:
        D: Accumulated cost matrix
    """
    N, M = C.shape
    D = np.zeros((N, M))
    D[:, 0] = np.cumsum(C[:, 0])
    D[0, :] = C[0, :]
    for n in range(1, N):
        for m in range(1, M):
            D[n, m] = C[n, m] + min(D[n-1, m], D[n, m-1], D[n-1, m-1])
    return D

D =  compute_accumulated_cost_matrix(C)
print(D)
print('b* =', D[-1, :].argmin())

def compute_optimal_warping_path(D):
    """Given an accumulated cost matrix, Compute the warping path for subsequence dynamic time warping with
    step sizes {(1, 0), (0, 1), (1, 1)}

    Notebook: C7/C7S2_SubsequenceDTW.ipynb

    Args:
        D: Accumulated cost matrix

    Returns
        P: Warping path (list of index pairs)
    """
    N, M = D.shape
    n = N - 1
    m = D[N - 1, :].argmin()
    P = [(n, m)]

    while n > 0:
        if m == 0:
            cell = (n - 1, 0)
        else:
            val = min(D[n-1, m-1], D[n-1, m], D[n, m-1])
            if val == D[n-1, m-1]:
                cell = (n-1, m-1)
            elif val == D[n-1, m]:
                cell = (n-1, m)
            else:
                cell = (n, m-1)
        P.append(cell)
        n, m = cell
    P.reverse()
    return np.array(P)
        
P = compute_optimal_warping_path(D)
print('Optimal warping path P =', P.tolist())

Cost matrix C =
[[2. 0. 0. 1. 2. 0. 1. 1.]
 [0. 2. 2. 1. 0. 2. 1. 3.]
 [0. 2. 2. 1. 0. 2. 1. 3.]]
[[2. 0. 0. 1. 2. 0. 1. 1.]
 [2. 2. 2. 1. 1. 2. 1. 4.]
 [2. 4. 4. 2. 1. 3. 2. 4.]]
b* = 4
Optimal warping path P = [[0, 2], [1, 3], [2, 4]]
